export const ADD_PRODUCT = "ADD PRODUCT";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_ERROR = "ADD_PRODUCT_ERROR";

export const START_DOWNLOAD_PRODUCTS = "START_DOWNLOAD_PRODUCTS";
export const DOWNLOAD_PRODUCTS_SUCCESS = "DOWNLOAD_PRODUCTS_SUCCESS";
export const DOWNLOAD_PRODUCTS_ERROR = "DOWNLOAD_PRODUCTS_ERROR";

export const OBTAIN_PRODUCT_TO_DELETE = "OBTAIN_PRODUCT_TO_DELETE";
export const PRODUCT_DELETED_SUCCESS = "PRODUCT_DELETED_SUCCESS";
export const PRODUCT_DELETED_ERROR = "PRODUCT_DELETED_ERROR";

export const OBTAIN_PRODUCT_TO_EDIT = "OBTAIN_PRODUCT_TO_EDIT";
export const START_EDIT_PRODUCT = "START_EDIT_PRODUCT";
export const PRODUCT_EDITED_SUCCESS = "PRODUCT_EDITED_SUCCESS";
export const PRODUCT_EDITED_ERROR = "PRODUCT_EDITED_ERROR";

export const SHOW_ALERT = "SHOW_ALERT";
export const HIDE_ALERT = "HIDE_ALERT";
